#pragma once

enum RendererErrorCode
{
    UNKNOWN_SHADER_UNIFORM_VARIABLE,
    SDL2DEVICE_SDL_INIT_ERROR,
    SDL2DEVICE_GLEW_INIT_ERROR,
    SDL2DEVICE_WINDOW_CREATION_ERROR,
    SDL2DEVICE_CONTEXT_CREATION_ERROR,
    SDL2DEVICE_NOT_SDL_CONTEXT,
    OPENGL_UNKNWON_BUFFER,
    OPENGL_UNKNWON_BUFFER_TARGET,
    OPENGL_UNSUPPORTED_BUFFER,
    OPENGL_UNSUPPORTED_BUFFER_OPERATION,
    OPENGL_MULTI_BUFFERING_NOT_SUPPORTED,
    OPENGL_NO_SHADER_BOUND,
    OPENGL_ATTRIBUTE_LOCATION_QUERY_FAILED,
};