#pragma once

enum RendererErrorCode
{
    SDL2DEVICE_SDL_INIT_ERROR,
    SDL2DEVICE_GLEW_INIT_ERROR,
    SDL2DEVICE_WINDOW_CREATION_ERROR,
    SDL2DEVICE_CONTEXT_CREATION_ERROR,
    SDL2DEVICE_NOT_SDL_CONTEXT,
    OPENGL_UNKNWON_BUFFER,
    OPENGL_UNKNWON_BUFFER_TARGET,
    OPENGL_UNSUPPORTED_BUFFER,
    OPENGL_UNSUPPORTED_BUFFER_OPERATION,
    OPENGL_MULTI_BUFFERING_NO_SUPPORRTED
};