#pragma once

enum RendererErrorCode
{
    SDL2DEVICE_SDL_INIT_ERROR,
    SDL2DEVICE_GLEW_INIT_ERROR,
    SDL2DEVICE_WINDOW_CREATION_ERROR,
    SDL2DEVICE_CONTEXT_CREATION_ERROR,
    SDL2DEVICE_NOT_SDL_CONTEXT
};