@startuml

class Resource
{
    id uint64
    content []byte
}

class File extends Resource
{
    path string
    name string
}

interface ResourceLoader<T>
{
    T load()
}

class FileSystemResourceLoader<File> implements ResourceLoader
{
    File load()
}


class FileSystemResourceLoader<File>
{
    File load()
}

ResourceLoader => Resource: creates
FileSystemResourceLoader => File: reads


class ResourcesManager
{
    resources[id]WeakPointer<Resource>
}

ResourcesManager ===> Resource: Holds
@enduml